### ISSUE TITLE
cmak uninstalled

### ISSUE THREAD

**Issue by natk9** [Websoft9/ansible-kafka#13]
![image](https://user-images.githubusercontent.com/40535348/134792389-9698fe38-d7fb-4e72-84d0-7d52cb2bacc2.png)
![image](https://user-images.githubusercontent.com/40535348/134792406-a436ea01-556a-4f2d-861b-e5851724e64f.png)
![image](https://user-images.githubusercontent.com/40535348/134869106-2155d676-1eb1-43ca-b5b7-752679793e46.png)

**Comment by qiaofeng1227** [comment]
cmak 官方镜像有误，需要使用自己编译镜像。
修改docker-cmak的镜像获取方式
