### ISSUE TITLE
Some versions of kafka component information cannot be output completely

### ISSUE THREAD

**Issue by morning-tan** [Websoft9/ansible-kafka#14]
**Describe the bug**

Kafka v2.2 & v2.3 can fully output the compnents information. But Kafka v0.10 & v1.1 can't, the version number of [kafka] is empty.

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [x] mcloud
- [ ] create instance from private image

## Bug source

- [ ] Bugs from installation 
- [ ] Bugs from first use
- [x] Other (You should describe it)   

## System Environment

**Application Version**

v0.10 & v1.1

**OS**

- [ ] Ubuntu18.x
- [x] Ubuntu20.x
- [ ] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [x] Aws
- [ ] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

![image](https://user-images.githubusercontent.com/54173243/162134962-05725285-3dc3-4801-a847-ad4ef672b323.png)

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by qiaofeng1227** [comment]
when kafka < 2.0 
```
ls /opt/kafka/libs | grep kafka_
```

**Comment by chendelin1982** [comment]
use docker image
