### ISSUE TITLE
add visible tools for kafka

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/ansible-kafka#2]
add visible tools for kafka：https://github.com/xaecbd/KafkaCenter

**Comment by chendelin1982** [comment]
Kafka Magic for Apache Kafka®
https://www.kafkamagic.com/pricing/
```
docker run -d --rm -p 8080:80 digitsy/kafka-magic
```
![Uploading image.png…]()

**Comment by chendelin1982** [comment]
https://github.com/yahoo/CMAK  star 9.8k fork 2.3k

**Comment by chendelin1982** [comment]
https://github.com/obsidiandynamics/kafdrop star 2k

**Comment by chendelin1982** [comment]
https://github.com/linkedin/Burrow star 2.8k

**Comment by chendelin1982** [comment]
https://github.com/tchiotludo/akhq star 1.8k

**Comment by chendelin1982** [comment]
kafka Ecosystem : https://cwiki.apache.org/confluence/display/KAFKA/Ecosystem
![Uploading image.png…]()

**Comment by qiaofeng1227** [comment]
docker version : https://hub.docker.com/r/hlebalbau/kafka-manager

kafka add `kafka-manager`  by default, add document with kafka-manager

docker_apps_cmak_port: 9005

**Comment by chendelin1982** [comment]
Done
