### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by jiaosir-cn** [Websoft9/ansible-kafka#3]
Project: kafka -t test
version: 2.6.0
Platform: AWS ubuntu 20.04&Linux2                  阿里云 ubuntu 20.04&CentOS7.9
ip: 35.153.255.6     100.25.158.77       8.210.101.38       47.242.142.84
Error Installation error
error:
```
TASK [role_kafka : Download Kafka] ************************************************************************
fatal: [100.25.158.77]: FAILED! => {"changed": false, "msg": "Failure downloading https://apachemirror.sg.wuchna.com/kafka/2.6.0/kafka_2.13-2.6.0.tgz, HTTP Error 404: Not Found"}
```
![image](https://user-images.githubusercontent.com/76861519/108957990-50167180-76ad-11eb-8ef0-5c2260747fce.png)

**Comment by chendelin1982** [comment]
Use apache.org url to replace  wuchna.com url  
Done
