### ISSUE TITLE
cmak connecting about more than 5mins

### ISSUE THREAD

**Issue by zengxc-1996** [Websoft9/ansible-kafka#5]
**Describe the bug**
`docker logs cmak:`
![image](https://user-images.githubusercontent.com/63622990/109589492-5beab380-7b45-11eb-9baa-835f233a7dd8.png)
5 minutes ago:
 ip: 9005 it's ok!

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [x] mcloud
- [ ] create instance from private image

## Bug source

- [ ] Bugs from installation 
- [x] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [ ] Ubuntu18.x
- [ ] Ubuntu20.x
- [x] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [ ] Aws
- [x] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

paste screenshot here

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by qiaofeng1227** [comment]
```
    w9meta_data=W9Meta_data()
  File "/root/private-operation/job/W9Meta_data.py", line 496, in __init__
    self.github_repository=self.repository_select('linux')
  File "/root/private-operation/job/W9Meta_data.py", line 599, in repository_select
    self.repositoryVersion = input("\n\t输入版本标号：")
KeyboardInterrupt
[root@VM-81-187-centos job]# python3 build.py -
```

**Comment by qiaofeng1227** [comment]
User Dockerfile install
