### ISSUE TITLE
Installation initialization error

### ISSUE THREAD

**Issue by jiaosir-cn** [Websoft9/ansible-kafka#6]
**Describe the bug**

Error during installation.
ip:  54.209.20.69  ,  47.243.41.131
## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [x] mcloud
- [ ] create instance from private image

## Bug source

- [x] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

v2.4.1

**OS**

- [ ] Ubuntu18.x
- [x] Ubuntu20.x
- [ ] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [x] Aws
- [x] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

## Bug reproduce

Options ：2.4.1

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 
TASK [role_common : Install PyMySQL on pip2] **************************************************************************************************************************************************
fatal: [47.243.41.131]: FAILED! => {"changed": false, "msg": "Unable to find any of pip2 to use.  pip needs to be installed."}

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot
![image](https://user-images.githubusercontent.com/76861519/110411081-e3e03880-80c4-11eb-8753-9bd23b2532a9.png)

paste screenshot here

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by qiaofeng1227** [comment]
Done
